// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/iptv_category.dart';
import 'models/iptv_channel_model.dart';
import 'models/iptv_countries.dart';
import 'models/iptv_streams_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6141506818141325021),
    name: 'IptvStreamModel',
    lastPropertyId: const obx_int.IdUid(8, 4418574192717313808),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5567038224878082864),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 703303736376503817),
        name: 'channel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6186362347568862007),
        name: 'feed',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 625294576537622166),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 427489790709137310),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1407264553124284141),
        name: 'referrer',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3498104272046116602),
        name: 'userAgent',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4418574192717313808),
        name: 'quality',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8885849303582669429),
    name: 'IptvCategoryModel',
    lastPropertyId: const obx_int.IdUid(4, 5719037960318546839),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7280134508962171799),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9146232158618219808),
        name: 'sId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2675874432822691774),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5719037960318546839),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1233119234780525391),
    name: 'IptvChannelModel',
    lastPropertyId: const obx_int.IdUid(11, 6026141704336702879),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1840215677079603032),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2549263818677920293),
        name: 'uid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4784922424771731889),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6003698768694661559),
        name: 'altNames',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8102350413486123555),
        name: 'network',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7867519213982361308),
        name: 'owners',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 520077301776490867),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6581960413316595116),
        name: 'categories',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2829662888631668524),
        name: 'isNsfw',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6067032697470530705),
        name: 'replacedBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6026141704336702879),
        name: 'website',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3850227890706146305),
    name: 'IptvCountry',
    lastPropertyId: const obx_int.IdUid(5, 5972756512529464006),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5719105448771380973),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6317690747607176048),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3021508313401402499),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6069239099486392256),
        name: 'languages',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5972756512529464006),
        name: 'flag',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 3850227890706146305),
    lastIndexId: const obx_int.IdUid(1, 5466935377735778867),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [3097030686985105360],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      3314507059721966729,
      19224298163257241,
      2794630567938360341,
      7919415786556083610,
      7636260935181869570,
      3364234047277932831,
      8807615531739619767,
      1307835606071389221,
      2762255916643283722,
      8509523171982464100,
      1702290633519257503,
      7823198736590497810,
      901263577084690309,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1, generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    IptvStreamModel: obx_int.EntityDefinition<IptvStreamModel>(
      model: _entities[0],
      toOneRelations: (IptvStreamModel object) => [],
      toManyRelations: (IptvStreamModel object) => {},
      getId: (IptvStreamModel object) => object.id,
      setId: (IptvStreamModel object, int id) {
        object.id = id;
      },
      objectToFB: (IptvStreamModel object, fb.Builder fbb) {
        final channelOffset = fbb.writeString(object.channel);
        final feedOffset = fbb.writeString(object.feed);
        final titleOffset = fbb.writeString(object.title);
        final urlOffset = fbb.writeString(object.url);
        final referrerOffset = fbb.writeString(object.referrer);
        final userAgentOffset = fbb.writeString(object.userAgent);
        final qualityOffset = fbb.writeString(object.quality);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, channelOffset);
        fbb.addOffset(2, feedOffset);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, urlOffset);
        fbb.addOffset(5, referrerOffset);
        fbb.addOffset(6, userAgentOffset);
        fbb.addOffset(7, qualityOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final channelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final feedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final referrerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final userAgentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final qualityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = IptvStreamModel(
          id: idParam,
          channel: channelParam,
          feed: feedParam,
          title: titleParam,
          url: urlParam,
          referrer: referrerParam,
          userAgent: userAgentParam,
          quality: qualityParam,
        );

        return object;
      },
    ),
    IptvCategoryModel: obx_int.EntityDefinition<IptvCategoryModel>(
      model: _entities[1],
      toOneRelations: (IptvCategoryModel object) => [],
      toManyRelations: (IptvCategoryModel object) => {},
      getId: (IptvCategoryModel object) => object.id,
      setId: (IptvCategoryModel object, int id) {
        object.id = id;
      },
      objectToFB: (IptvCategoryModel object, fb.Builder fbb) {
        final sIdOffset = fbb.writeString(object.sId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = IptvCategoryModel(
          id: idParam,
          sId: sIdParam,
          name: nameParam,
          description: descriptionParam,
        );

        return object;
      },
    ),
    IptvChannelModel: obx_int.EntityDefinition<IptvChannelModel>(
      model: _entities[2],
      toOneRelations: (IptvChannelModel object) => [],
      toManyRelations: (IptvChannelModel object) => {},
      getId: (IptvChannelModel object) => object.id,
      setId: (IptvChannelModel object, int id) {
        object.id = id;
      },
      objectToFB: (IptvChannelModel object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final nameOffset = fbb.writeString(object.name);
        final altNamesOffset = fbb.writeList(
          object.altNames.map(fbb.writeString).toList(growable: false),
        );
        final networkOffset = object.network == null
            ? null
            : fbb.writeString(object.network!);
        final ownersOffset = fbb.writeList(
          object.owners.map(fbb.writeString).toList(growable: false),
        );
        final countryOffset = object.country == null
            ? null
            : fbb.writeString(object.country!);
        final categoriesOffset = fbb.writeList(
          object.categories.map(fbb.writeString).toList(growable: false),
        );
        final replacedByOffset = object.replacedBy == null
            ? null
            : fbb.writeString(object.replacedBy!);
        final websiteOffset = object.website == null
            ? null
            : fbb.writeString(object.website!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, altNamesOffset);
        fbb.addOffset(4, networkOffset);
        fbb.addOffset(5, ownersOffset);
        fbb.addOffset(6, countryOffset);
        fbb.addOffset(7, categoriesOffset);
        fbb.addBool(8, object.isNsfw);
        fbb.addOffset(9, replacedByOffset);
        fbb.addOffset(10, websiteOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final altNamesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final networkParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final ownersParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final categoriesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 18, []);
        final isNsfwParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final replacedByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final websiteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final object = IptvChannelModel(
          id: idParam,
          uid: uidParam,
          name: nameParam,
          altNames: altNamesParam,
          network: networkParam,
          owners: ownersParam,
          country: countryParam,
          categories: categoriesParam,
          isNsfw: isNsfwParam,
          replacedBy: replacedByParam,
          website: websiteParam,
        );

        return object;
      },
    ),
    IptvCountry: obx_int.EntityDefinition<IptvCountry>(
      model: _entities[3],
      toOneRelations: (IptvCountry object) => [],
      toManyRelations: (IptvCountry object) => {},
      getId: (IptvCountry object) => object.id,
      setId: (IptvCountry object, int id) {
        object.id = id;
      },
      objectToFB: (IptvCountry object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final codeOffset = fbb.writeString(object.code);
        final languagesOffset = fbb.writeList(
          object.languages.map(fbb.writeString).toList(growable: false),
        );
        final flagOffset = fbb.writeString(object.flag);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, codeOffset);
        fbb.addOffset(3, languagesOffset);
        fbb.addOffset(4, flagOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final languagesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final flagParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = IptvCountry(
          id: idParam,
          name: nameParam,
          code: codeParam,
          languages: languagesParam,
          flag: flagParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [IptvStreamModel] entity fields to define ObjectBox queries.
class IptvStreamModel_ {
  /// See [IptvStreamModel.id].
  static final id = obx.QueryIntegerProperty<IptvStreamModel>(
    _entities[0].properties[0],
  );

  /// See [IptvStreamModel.channel].
  static final channel = obx.QueryStringProperty<IptvStreamModel>(
    _entities[0].properties[1],
  );

  /// See [IptvStreamModel.feed].
  static final feed = obx.QueryStringProperty<IptvStreamModel>(
    _entities[0].properties[2],
  );

  /// See [IptvStreamModel.title].
  static final title = obx.QueryStringProperty<IptvStreamModel>(
    _entities[0].properties[3],
  );

  /// See [IptvStreamModel.url].
  static final url = obx.QueryStringProperty<IptvStreamModel>(
    _entities[0].properties[4],
  );

  /// See [IptvStreamModel.referrer].
  static final referrer = obx.QueryStringProperty<IptvStreamModel>(
    _entities[0].properties[5],
  );

  /// See [IptvStreamModel.userAgent].
  static final userAgent = obx.QueryStringProperty<IptvStreamModel>(
    _entities[0].properties[6],
  );

  /// See [IptvStreamModel.quality].
  static final quality = obx.QueryStringProperty<IptvStreamModel>(
    _entities[0].properties[7],
  );
}

/// [IptvCategoryModel] entity fields to define ObjectBox queries.
class IptvCategoryModel_ {
  /// See [IptvCategoryModel.id].
  static final id = obx.QueryIntegerProperty<IptvCategoryModel>(
    _entities[1].properties[0],
  );

  /// See [IptvCategoryModel.sId].
  static final sId = obx.QueryStringProperty<IptvCategoryModel>(
    _entities[1].properties[1],
  );

  /// See [IptvCategoryModel.name].
  static final name = obx.QueryStringProperty<IptvCategoryModel>(
    _entities[1].properties[2],
  );

  /// See [IptvCategoryModel.description].
  static final description = obx.QueryStringProperty<IptvCategoryModel>(
    _entities[1].properties[3],
  );
}

/// [IptvChannelModel] entity fields to define ObjectBox queries.
class IptvChannelModel_ {
  /// See [IptvChannelModel.id].
  static final id = obx.QueryIntegerProperty<IptvChannelModel>(
    _entities[2].properties[0],
  );

  /// See [IptvChannelModel.uid].
  static final uid = obx.QueryStringProperty<IptvChannelModel>(
    _entities[2].properties[1],
  );

  /// See [IptvChannelModel.name].
  static final name = obx.QueryStringProperty<IptvChannelModel>(
    _entities[2].properties[2],
  );

  /// See [IptvChannelModel.altNames].
  static final altNames = obx.QueryStringVectorProperty<IptvChannelModel>(
    _entities[2].properties[3],
  );

  /// See [IptvChannelModel.network].
  static final network = obx.QueryStringProperty<IptvChannelModel>(
    _entities[2].properties[4],
  );

  /// See [IptvChannelModel.owners].
  static final owners = obx.QueryStringVectorProperty<IptvChannelModel>(
    _entities[2].properties[5],
  );

  /// See [IptvChannelModel.country].
  static final country = obx.QueryStringProperty<IptvChannelModel>(
    _entities[2].properties[6],
  );

  /// See [IptvChannelModel.categories].
  static final categories = obx.QueryStringVectorProperty<IptvChannelModel>(
    _entities[2].properties[7],
  );

  /// See [IptvChannelModel.isNsfw].
  static final isNsfw = obx.QueryBooleanProperty<IptvChannelModel>(
    _entities[2].properties[8],
  );

  /// See [IptvChannelModel.replacedBy].
  static final replacedBy = obx.QueryStringProperty<IptvChannelModel>(
    _entities[2].properties[9],
  );

  /// See [IptvChannelModel.website].
  static final website = obx.QueryStringProperty<IptvChannelModel>(
    _entities[2].properties[10],
  );
}

/// [IptvCountry] entity fields to define ObjectBox queries.
class IptvCountry_ {
  /// See [IptvCountry.id].
  static final id = obx.QueryIntegerProperty<IptvCountry>(
    _entities[3].properties[0],
  );

  /// See [IptvCountry.name].
  static final name = obx.QueryStringProperty<IptvCountry>(
    _entities[3].properties[1],
  );

  /// See [IptvCountry.code].
  static final code = obx.QueryStringProperty<IptvCountry>(
    _entities[3].properties[2],
  );

  /// See [IptvCountry.languages].
  static final languages = obx.QueryStringVectorProperty<IptvCountry>(
    _entities[3].properties[3],
  );

  /// See [IptvCountry.flag].
  static final flag = obx.QueryStringProperty<IptvCountry>(
    _entities[3].properties[4],
  );
}
